[package]
name = "ikafka"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.8"
regex = "1.6.0"
chrono = "0.4.19"
clap = { version = "3.2.12", features = ["derive"] }
colored = "2.0.0"
